stages:
  - build
  # - deploy

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: "/certs"
  IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
  KUBECONFIG_FILE: $KUBECONFIG

# Build Docker image
build:
  stage: build
  image: docker:28.3.3
  services:
    - docker:28.3.3-dind
  before_script:  
    - echo $CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER --password-stdin $CI_REGISTRY
  script:
    # Update api.js
    - sed -i 's|http://localhost:5169/api|https://ecommerceapi.bunlong.site/api|g' src/services/api.js

    - sed -i 's|http://localhost:5169|https://ecommerceapi.bunlong.site|g' src/services/chatService.js

    # Verify the connection string was updated
    - cat src/services/api.js | grep "api"
    - cat src/services/chatService.js | grep "baseUrl"

    # . at then end: is used the current directory to look for the Dockerfile
    - docker build -t $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA -t $CI_REGISTRY_IMAGE:latest .
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
    - docker push $CI_REGISTRY_IMAGE:latest
  only:
    - main
    - develop